//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patient_Transport_EF.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostische_Onderzoeken
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diagnostische_Onderzoeken()
        {
            this.Transport_task = new HashSet<Transport_task>();
        }
    
        public int Pk_Id { get; set; }
        public string patient { get; set; }
        public Nullable<bool> ct { get; set; }
        public Nullable<bool> nmr { get; set; }
        public Nullable<bool> rx { get; set; }
        public Nullable<bool> echografie { get; set; }
        public Nullable<bool> onbekend { get; set; }
        public string andere { get; set; }
        public string bevindingen { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_complete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transport_task> Transport_task { get; set; }
    }
}
