//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patient_Transport_EF.Models.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFEntities2 : DbContext
    {
        public EFEntities2()
            : base("name=EFEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Diagnostische_Onderzoeken> Diagnostische_Onderzoeken { get; set; }
        public virtual DbSet<Request_Status> Request_Status { get; set; }
        public virtual DbSet<Request_Type> Request_Type { get; set; }
        public virtual DbSet<Transport_task> Transport_task { get; set; }
    }
}
