//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patient_Transport_EF.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Status
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request_Status()
        {
            this.Transport_task = new HashSet<Transport_task>();
            this.Request_Status1 = new HashSet<Request_Status>();
        }
    
        public int Fk_Request_Type { get; set; }
        public int Pk_Id { get; set; }
        public string description { get; set; }
        public int next { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transport_task> Transport_task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Status> Request_Status1 { get; set; }
        public virtual Request_Status Request_Status2 { get; set; }
        public virtual Request_Type Request_Type { get; set; }
    }
}
