//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patient_Transport_EF.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request_Type()
        {
            this.Request_Status = new HashSet<Request_Status>();
            this.Transport_task = new HashSet<Transport_task>();
        }
    
        public int PK_Id { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public bool Fk_Diagnostische_Onderzoeken { get; set; }
        public bool patient { get; set; }
        public bool notities { get; set; }
        public bool datum_van_aanvraag { get; set; }
        public bool datum_behandeld { get; set; }
        public bool huidige_klachten { get; set; }
        public bool aan_dokter { get; set; }
        public bool andere_notas { get; set; }
        public bool aanvragende_geneesheer { get; set; }
        public bool patient_wordt_behandeld_voor { get; set; }
        public bool bevindingen_en_advies { get; set; }
        public bool relevante_klinische_inlichtingen { get; set; }
        public bool diagnostische_vraagstelling { get; set; }
        public bool transport_te_voet { get; set; }
        public bool transport_rolstoel { get; set; }
        public bool tarnsport_bed { get; set; }
        public bool zwanger { get; set; }
        public bool diabeet { get; set; }
        public bool implantaat { get; set; }
        public bool nierinsufficientie { get; set; }
        public bool allergie { get; set; }
        public bool andere { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Status> Request_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transport_task> Transport_task { get; set; }
    }
}
