//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patient_Transport_EF.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport_task
    {
        public int PK_Id { get; set; }
        public int FK_Request_Type { get; set; }
        public Nullable<int> Fk_Diagnostische_Onderzoeken { get; set; }
        public int FK_Request_Status { get; set; }
        public bool is_high_priority { get; set; }
        public string employee_assigned { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_complete { get; set; }
        public string van { get; set; }
        public string naar { get; set; }
        public string patient { get; set; }
        public string notities { get; set; }
        public Nullable<System.DateTime> datum_van_aanvraag { get; set; }
        public Nullable<System.DateTime> datum_behandeld { get; set; }
        public string huidige_klachten { get; set; }
        public Nullable<int> aan_dokter { get; set; }
        public string andere_notas { get; set; }
        public string aanvragende_geneesheer { get; set; }
        public string patient_wordt_behandeld_voor { get; set; }
        public string bevindingen_en_advies { get; set; }
        public string relevante_klinische_inlichtingen { get; set; }
        public string diagnostische_vraagstelling { get; set; }
        public Nullable<bool> transport_te_voet { get; set; }
        public Nullable<bool> transport_rolstoel { get; set; }
        public Nullable<bool> tarnsport_bed { get; set; }
        public Nullable<bool> zwanger { get; set; }
        public Nullable<bool> diabeet { get; set; }
        public Nullable<bool> implantaat { get; set; }
        public Nullable<bool> nierinsufficientie { get; set; }
        public string allergie { get; set; }
        public string andere { get; set; }
    
        public virtual Diagnostische_Onderzoeken Diagnostische_Onderzoeken { get; set; }
        public virtual Request_Status Request_Status { get; set; }
        public virtual Request_Type Request_Type { get; set; }
    }
}
